### ISSUE TITLE
coverage rule result in different outputs in PIP

### ISSUE THREAD

**Issue by randrescastaneda** [worldbank/pip#19]
Will the coverage rule result in different outputs in PIP? For example, global poverty estimate for 2018 has been censored out in `povcalnet wb, clear` but is available in `pip wb, clear`

@tsamuel321 , @tonyfujs , @Aeilert , @Tefera19

**Comment by randrescastaneda** [comment]
@Aeilert , we are using the coverage rule that Daniel gave us, right?

**Comment by Aeilert** [comment]
Hi @randrescastaneda 

The current coverage rule in PIP lacks the additional rule of sufficient coverage in LIC/LMIC countries for the global numbers, which why WLD 2018 is not automatically censored in the ingestion pipeline. It is has however been manually added to censoring file that is on TFS and will be censored in PROD. Which API are you pulling from? 

We are btw working on implementing the correct coverage rule in pipdm, but turns we have other bugs and issue as well (in addition to the missing LIC/LMIC rule).

**Comment by tsamuel321** [comment]
Censoring works okay in PROD.
