### ISSUE TITLE
small diff in global aggregate

### ISSUE THREAD

**Issue by randrescastaneda** [worldbank/pip#20]
Regional and global poverty estimates are not identical between the old [povcalnet] and new [pip] command. For example, headcount ratio for the world in 2017 is 9.27% or 9.29%, respectively

@tsamuel321 @tonyfujs @Aeilert @Tefera19

**Comment by randrescastaneda** [comment]
I think the differnece is due to the updates on small updated in microda, right @Aeilert ?

**Comment by randrescastaneda** [comment]
Working on it. 

@Tefera19 , Please make sure you address this. 

Thanks.

**Comment by Aeilert** [comment]
@randrescastaneda : There is a small difference in the total number of poor between PovcalNet sept 2021 (697) and PIP soft launch (698). I would guess that also affects the ratio. 

FYI: I think the remaining diff here mainly stems from LAC, possibly due to handling of u/r surveys, but we haven't pinpointed the issue. For soft launch we should be fine anyways.

**Comment by Tefera19** [comment]
@randrescastaneda : I have checked the ado file and I've found any problem. Here is how the aggregate data is pulled from the server.

import delimit using "https://apiv2qa.worldbank.org/pip/v1/pip?year=all&country=all&reporting_level=all&povline=1.9&group_by=wb&format=csv", clear varn(1)

Thanks

**Comment by tonyfujs** [comment]
@randrescastaneda @Tefera19 For group_by=wb, reporting_level should be equal to "national", not "all"
Hopefully this confusion will disappear once the `pip-grp` endpoint is correctly mapped

**Comment by randrescastaneda** [comment]
> @randrescastaneda @Tefera19 For group_by=wb, reporting_level should be equal to "national", not "all" Hopefully this confusion will disappear once the `pip-grp` endpoint is correctly mapped

But this won't solve the problem. Right?  I mean, the difference in the global poverty rate is not due to this, is it?

Best, 
Andres

**Comment by Tefera19** [comment]
I have tried reporting_level = national and it hasn't changed the result.

Best,
Tefera

**Comment by tsamuel321** [comment]
Deprecated.
