### ISSUE TITLE
Population data in PIP are not in millions

### ISSUE THREAD

**Issue by randrescastaneda** [worldbank/pip#22]

**Comment by randrescastaneda** [comment]
HI Samuel, 

Do we need it in millions? Is it ok if pop is in million using the option  `povclnet_format`, so that if the user types `pip, povcalnet_format clear` population will be in millions, but if they only type `pip, clear` then it will be in the current format?

Best, 


@tsamuel321 , @tonyfujs , @Aeilert, @Tefera19

**Comment by tsamuel321** [comment]
The population data are still not in millions, but I don't think anyone now wants us to change it to millions.
