### ISSUE TITLE
GNB 1991 poverty rate not showing

### ISSUE THREAD

**Issue by danielmahler** [worldbank/pip#27]
I noticed an odd thing happening with pip.ado. Not sure if you are aware of it
 
pip, country(GNB) year(1991) povline(1.9 3.2 5.5) clear

br country_code poverty_line headcount

The poverty line and rate is missing for 5.5 for some reason...

**Comment by danielmahler** [comment]
Probably a related issue: when I run this line of code, poverty_line is missing for GNB from 1981-1992...

pip, country(all) povline(1.9 3.2 5.5) year(all) fillgaps clear

**Comment by Tefera19** [comment]
Hi Andres,

I used the api endpoint and got the same result, the issue might be from the serve side.
import delimited "https://api.worldbank.org/pip/v1/pip?year=1991&country=GNB&reporting_level=all&povline=5.5 &format=csv", clear

@randrescastaneda

**Comment by tsamuel321** [comment]
I think this issue can be ignored. 

//Finding: When the poverty line queried is too high, for some reason a poverty rate is not returned. GNB1991 is binned data (see code below). It could be that there are some restrictions in the code for grouped data that are not satisfied. In PovcalNet, -1 is returned as the poverty rate, which is undefined. Makes sense to me that these estimates are missing in PIP.

*GNB 1991 poverty rate not showing
pip, country(GNB) year(1991) povline(1.9 3.2 5.46) server(dev) ppp_year(2011) clear
br country_code poverty_line headcount 

pip, country(GNB) year(1991) povline(1.9 3.2 5.5) server(dev) ppp_year(2011) clear
br country_code poverty_line headcount 

pip, country(GNB) year(1991) povline(2.15 3.65 6.4) server(dev) ppp_year(2017) clear
br country_code poverty_line headcount 

pip, country(GNB) year(1991) povline(2.15 3.65 6.5) server(dev) ppp_year(2017) clear
br country_code poverty_line headcount 

pip, country(GNB) year(1991) povline(2.15 3.65 6.5) server(dev) ppp_year(2017) clear
br country_code poverty_line headcount 

pip, country(GNB) year(1991) povline(2.15 3.65 6.85) clear
br country_code poverty_line headcount 

//Finding: When the poverty line queried is too high, for some reason a poverty rate is not returned. GNB1991 is binned data (see code below). It could be that there are some restrictions in the code for grouped data that are not satisfied. In PovcalNet, -1 is returned as the poverty rate, which is undefined. Makes sense to me that these estimates are missing in PIP.

pcn load, countries(gnb) year(1991) clear
count 
br 

povcalnet, country(GNB) year(1991) clear povline(5.5)

**Comment by Tefera19** [comment]
Hi Andres,

This issue has been resolved with the latest pip version.
