### ISSUE TITLE
1980 Argentina no returns with pip.ado

### ISSUE THREAD

**Issue by danielmahler** [worldbank/pip#29]
Hi all,

I found something strange going on with the povcalnet.ado. Probably I'm doing something wrong, but thought I would check:
When I do this query, there is an estimate for ARG in 1980:
pip, country(arg) year(all) clear
Yet when I try to query the 1980 estimate directly, I get an error
pip, country(arg) year(1980) clear

Warning: 
the countries and years selected do not match any year available.
invalid syntax

Do you know what's going on?

**Comment by tsamuel321** [comment]
Issue solved, and it does not happen for all surveys for all countries before 1981 (see code below)

drop _all
tempfile df
save `df', empty

pip, country(all) year(all) clear
keep if year<1981

keep country_code year headcount reporting_level
rename headcount hc 

tempfile df_hist 
save `df_hist'

use `df_hist', clear 
count 

forvalues row = 1/`r(N)'{
	
	use `df_hist', clear 
	loc ccc 	= country_code[`row']
	loc yyy		= year[`row']
	loc cov     = reporting_level[`row']
	
	pip, country(`ccc') year(`yyy') coverage(`cov') clear
	keep country_code year headcount reporting_level
	rename headcount hc_check
	
	append using `df'

	tempfile df 
	save `df', replace
}

use `df', clear 
merge 1:1 country_code year reporting_level using `df_hist', nogen 
count 

//Check if headcount ratio is identical in both cases
gen double d_hc = hc/hc_check 
sum d_hc 
assert `r(mean)' == 1
