### ISSUE TITLE
TZA 2017.92 issue in PIP.ado

### ISSUE THREAD

**Issue by danielmahler** [worldbank/pip#30]
Hi all,

I noticed something strange with the 2017-18 survey for Tanzania. It can only get queried in 2018. Of the three lines below, only the first one works (I think it should be the reverse, only the first two should work). Let me know if I got something wrong :)

pip, country(TZA) year(2017.92) clear
pip, country(TZA) year(2017) clear
pip, country(TZA) year(2018) clear

**Comment by Tefera19** [comment]
Hi Andres,

Currently, pip commands pull estimates based on reporting_year not based on survey_year. For example, for Tanzania available reporting years are 1991, 2000, 2007, 2011, and 2018 and available survey years are 1991.92, 2000.33, 2007, 2011.77 and 2017.92.  So, pip commands would allow pull data for Tanzania only for 1991, 2000, 2007, 2011 and 2018 (these are available years in reporting_year variable). The issue can be resolved by switching survey year information to pull data from the server. Would you want me to update the pip command to pull data based on the survey year?

**Comment by Tefera19** [comment]
Hi @randrescastaneda,

The 2017.92 welfare time supposed to resolve to the integer part of the fraction year as the rest of similar year format. In the Tanzania data, 2017.92 is associated to 2018 reference year, so would it be possible to change this in the source data?

Tefera

**Comment by congminh6** [comment]
Hi Tefera,

I think TZA2917/8 is a special case. The fieldwork is dec17-Dec18, and most of the welfare collection period is in 2018. The Country team, region, NSO, refers to the reporting of data as 2018.

Please let me know if there is any comment/question.

Best,
Minh

**Comment by randrescastaneda** [comment]
Hi @danielmahler , 

Based on Minh's response, I think we have two options:
1. Leave it as is
2. Hardcode the Stata wrapper only for TZA 2018

I like the first option because it is clean and because, I think, most people will request 2018 rather than 2017.92 or 2017. If you agree, please feel free to close this issue. Otherwise, I think we could bring this issue to the GPID meeting to get some advice. 

Best,

**Comment by congminh6** [comment]
Hi all,

In the API, do we use the report year or the survey year for the request? If it is reporting year then it is 2018 and the same as-is. If I remember correctly, there is another case like this, welfare data is collected for the second half of the data collection/fieldwork so we report on the T+1.

Best,
Minh
